## 4-е домашнее задание - Библиотека numpy

Подпишите этот блокнот: укажите ФИО и номер группы. Выполненное задание загрузите в свой репозиторий «<b>Spring2023Python</b>» в github в папку "<b>homework04</b>".  

Перед выполнением этого домашнего задания полезно прочитать про возможности и основные методы библиотеки numpy:  
http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy  


1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [5]:
import numpy as np
np.linspace(-1.3, 2.5, num=64)

array([-1.3       , -1.23968254, -1.17936508, -1.11904762, -1.05873016,
       -0.9984127 , -0.93809524, -0.87777778, -0.81746032, -0.75714286,
       -0.6968254 , -0.63650794, -0.57619048, -0.51587302, -0.45555556,
       -0.3952381 , -0.33492063, -0.27460317, -0.21428571, -0.15396825,
       -0.09365079, -0.03333333,  0.02698413,  0.08730159,  0.14761905,
        0.20793651,  0.26825397,  0.32857143,  0.38888889,  0.44920635,
        0.50952381,  0.56984127,  0.63015873,  0.69047619,  0.75079365,
        0.81111111,  0.87142857,  0.93174603,  0.99206349,  1.05238095,
        1.11269841,  1.17301587,  1.23333333,  1.29365079,  1.35396825,
        1.41428571,  1.47460317,  1.53492063,  1.5952381 ,  1.65555556,
        1.71587302,  1.77619048,  1.83650794,  1.8968254 ,  1.95714286,
        2.01746032,  2.07777778,  2.13809524,  2.1984127 ,  2.25873016,
        2.31904762,  2.37936508,  2.43968254,  2.5       ])

2.	Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [4]:
n = 10
arr = np.arange(0,3 * n)
arr = arr % 3 + 1
arr


array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1,
       2, 3, 1, 2, 3, 1, 2, 3])

3.	Создайте массив первых 10 нечетных целых чисел.

In [8]:
n = 10
arr = np.arange(1,2 * n, 2)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [9]:
m = np.zeros((10,10))
m[0, :] = 1
m[9, :] = 1
m[:, 0] = 1
m[:, 9] = 1
m


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [10]:
m = np.zeros((8,8))
m[::2,::2] = 1
m[1::2,1::2] = 1
m

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [11]:
n = 10
m = np.zeros((n,n))
for i in range (n):
    for j in range (n):
        m[i][j] = i + j
m

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       [ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
       [ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.],
       [ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.],
       [ 6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15.],
       [ 7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16.],
       [ 8.,  9., 10., 11., 12., 13., 14., 15., 16., 17.],
       [ 9., 10., 11., 12., 13., 14., 15., 16., 17., 18.]])

7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [12]:
v1 = np.array([[1, 2, 3]])
v2 = np.array([[1], [2], [3]])
m1 = np.array([[1, 2], [2, 1], [3, 9]])
m2 = np.array([[1, 2, 3], [1, 2, 3]])
print(np.dot(v1, v2))
print(np.dot(v1, m1))
print(np.dot(m1, m2))

[[14]]
[[14 31]]
[[ 3  6  9]
 [ 3  6  9]
 [12 24 36]]


8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [3]:
num_of_steps = 1/0.05

cosines = np.cos(np.linspace(0, 1, int(num_of_steps)))
sines = np.sin(np.linspace(0, 1, int(num_of_steps)))
result = list(cosines) + list(sines)
result.sort()
print(result)

[0.0, 0.05260728333807213, 0.10506887376594912, 0.15723948186175024, 0.20897462406278547, 0.2601310228046501, 0.3105670033203749, 0.3601428860007191, 0.40872137322898616, 0.4561679296190457, 0.5023511546035125, 0.5403023058681398, 0.547143146340223, 0.5838216399741468, 0.5904198559291864, 0.625724112908743, 0.6320614309590333, 0.6658936781316236, 0.6719525474315213, 0.7042190882928544, 0.7099827291448582, 0.7405942033261461, 0.7460466536513234, 0.7749182843977933, 0.7800444439418607, 0.8070962728972044, 0.8118819450498316, 0.8370390536963741, 0.8414709848078965, 0.8646637019492132, 0.8898937127472434, 0.9126592129956349, 0.9328971549228098, 0.9505514906876966, 0.9655733276010717, 0.9779210635311101, 0.9875605021181478, 0.9944649474795756, 0.9986152781425827, 1.0]


9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [11]:
m = np.random.rand(3,5)*4-1
m

array([[ 1.71552794,  0.96497995, -0.79403847, -0.28974927,  2.49226454],
       [-0.68868162, -0.02886519, -0.85045802, -0.6887653 , -0.59232748],
       [ 0.04762224,  1.46425655, -0.0398373 ,  2.37872092, -0.08863487]])

10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [14]:
print(m.sum())
print(m.sum(0))
print(m.sum(1))
print(m.mean(1))
print(m.var(1))
print(m.std(1))

20.562859709765274
[4.00988524 3.74010645 4.65823186 6.05396522 2.10067094]
[10.41669241  2.45578045  7.69038685]
[2.08333848 0.49115609 1.53807737]
[0.16776744 0.39475957 0.55993903]
[0.40959423 0.62829895 0.74829074]


11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [12]:
for i in range(len(m)):
    m[i, :] = (m[i, :] - np.mean(m[i])) / np.std(m[i])
m

array([[ 0.73514911,  0.12052771, -1.31992697, -0.90696613,  1.37121628],
       [-0.42015041,  1.91215022, -0.9919931 , -0.4204462 , -0.07956051],
       [-0.70597965,  0.71301916, -0.79358517,  1.62900985, -0.84246418]])

12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [13]:


col = m[:, 3]
sorted = np.argsort(m[:, 3])
temp = np.zeros((3,))
for i in range(3):
    temp[i] = col[sorted[i]]
m[:, 3] = temp
m



array([[ 0.73514911,  0.12052771, -1.31992697, -0.90696613,  1.37121628],
       [-0.42015041,  1.91215022, -0.9919931 , -0.4204462 , -0.07956051],
       [-0.70597965,  0.71301916, -0.79358517,  1.62900985, -0.84246418]])

13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [15]:
b = np.dot(np.transpose(m), m)
c = np.dot(m, np.transpose(m))

print(f'Матрица B: {b}\n\nМатрица C: {c}')

Матрица B: [[ 1.21537785 -1.21816187  0.00669815 -1.6401525   1.63623838]
 [-1.21816187  4.17924169 -2.62176902  0.24824438 -0.58755518]
 [ 0.00669815 -2.62176902  3.35603494  0.32145072 -1.06241479]
 [-1.6401525   0.24824438  0.32145072  3.65303566 -2.58257826]
 [ 1.63623838 -0.58755518 -1.06241479 -2.58257826  2.59630986]]

Матрица C: [[ 5.          1.50318813 -2.01824463]
 [ 1.50318813  5.          1.82936426]
 [-2.01824463  1.82936426  5.        ]]


14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [16]:
np.sum(np.diagonal(b)) + np.sum(np.diagonal(c))



30.000000000000004

15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


In [18]:
det_b = np.linalg.det(b)
det_c = np.linalg.det(c)
rank_a = np.linalg.matrix_rank(m)
rank_b = np.linalg.matrix_rank(b)
rank_c = np.linalg.matrix_rank(c)
w_b, v_b = np.linalg.eig(b)
w_c, v_b = np.linalg.eig(c)

print(f'Ранг матрицы А: {rank_a}\nДетерминант матрицы B: {det_b}\nРанг матрицы B: {rank_b}\n' \
      f'Спектр матрицы B: {w_b}\nДетерминант матрицы C: {det_c}\nРанг матрицы C: {rank_c}\n' \
      f'Спектр матрицы C: {w_c}\n')


Ранг матрицы А: 3
Детерминант матрицы B: -6.8763881214315906e-31
Ранг матрицы B: 3
Спектр матрицы B: [ 7.09025853e+00  6.48520154e+00  1.42453993e+00  3.99682213e-16
 -1.46542331e-17]
Детерминант матрицы C: 65.5028468020693
Ранг матрицы C: 3
Спектр матрицы C: [1.42453993 6.48520154 7.09025853]



16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять два из следующих примеров:  
- один с номером, сгенерированным случайным образом с помощью функции np.random.randint(9), в качестве seed для генератора случайных чисел взять номер своего студенческого билета. 
- второй номер - под номером 9, несобственный интерграл. Подумайте, как сделать подбор шага интегрирования адаптивным.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        <td> 9) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        </tr>
</table>

In [19]:
np.random.seed(17)
print(np.random.randint(9))
def f(x):
    return (x**2 + 3)/(x-2)

def integral(f, a, b, dx):
    """
    Ввод: функция f(x), начало и конец отрезка [a;b], шаг интегрирования
    
    Вывод: значение интеграла функции f(x) на отрезке [a;b]
    """
    N = int((b-a) / dx)  # количество шагов
    xk = np.linspace(a, b, N)  # точки
    rectan = dx*np.sum(f(xk))  # решение методом прямоугольников
    trapezoid = dx/2*(f(dx) + 2*np.sum(f(xk[1:-1])) + f(xk[-1]))  # решение методом трапеций
    simp = dx/3*(f(dx) + 2*np.sum(f(xk[2:-1:2])) + 4*np.sum(f(xk[1:-2:2])) + f(xk[-1]))  # решение методом Симпсона
    return f"{rectan}, {trapezoid}, {simp} при шаге интегрирования {dx}"

anal_solution = np.float64(10.35203026391961716592062485020723)  # аналитическое решение
print(f"{anal_solution} - аналитическое решение функции f(x) на отрезке [3;4]")

for i in range(6):
    print(integral(f, 3, 4, 0.1 * 0.1**i))

1
10.352030263919618 - аналитическое решение функции f(x) на отрезке [3;4]
10.396680892636775, 8.642470366320985, 8.54599876273251 при шаге интегрирования 0.1
10.252534300917352, 10.077496361218863, 9.97319443934826 при шаге интегрирования 0.010000000000000002
10.342076641768477, 10.324576266330759, 10.314158283257582 при шаге интегрирования 0.0010000000000000002
10.351034862242713, 10.349284858492275, 10.348243178696709 при шаге интегрирования 0.00010000000000000003
10.351930723358093, 10.35175572332059, 10.351651556522672 при шаге интегрирования 1.0000000000000003e-05
10.352020309859533, 10.352002809859153, 10.351992393191178 при шаге интегрирования 1.0000000000000004e-06


In [20]:


def f(x):
    return 1/np.sqrt(2+3*x-2*x**2, where = x!=2)

def integral(f, a, b, dx):
    """
    Ввод: функция f(x), начало и конец отрезка [a;b], шаг интегрирования
    
    Вывод: значение интеграла функции f(x) на отрезке [a;b]
    """
    N = int((b-a) / dx)  # количество шагов
    xk = np.linspace(a, b, N)  # точки
    rectan = dx*np.sum(f(xk))  # решение методом прямоугольников
    trapezoid = dx/2*(f(dx) + 2*np.sum(f(xk[1:-1])) + f(xk[-1]))  # решение методом трапеций
    simp = dx/3*(f(dx) + 2*np.sum(f(xk[2:-1:2])) + 4*np.sum(f(xk[1:-2:2])) + f(xk[-1]))  # решение методом Симпсона
    return f"{rectan}, {trapezoid}, {simp} при шаге интегрирования {dx}"

anal_solution = np.float64(1.110720734539591561753970247515173)  # аналитическое решение
print(f"{anal_solution} - аналитическое решение функции f(x) на отрезке [3/4;2]")

for i in range(6):
    print(integral(f, np.float64(3/4), 2, 0.1 * 0.1**i))

1.1107207345395915 - аналитическое решение функции f(x) на отрезке [3/4;2]
0.8238512126812755, inf, inf при шаге интегрирования 0.1
1.0322244184751246, inf, inf при шаге интегрирования 0.010000000000000002
1.089198631758892, inf, inf при шаге интегрирования 0.0010000000000000002
1.1041017867496095, inf, inf при шаге интегрирования 0.00010000000000000003
1.1086415845859037, inf, inf при шаге интегрирования 1.0000000000000003e-05
inf, inf, inf при шаге интегрирования 1.0000000000000004e-06


/tmp/ipykernel_4177/2874173550.py:2: RuntimeWarning: overflow encountered in scalar divide
  return 1/np.sqrt(2+3*x-2*x**2, where = x!=2)
/tmp/ipykernel_4177/2874173550.py:2: RuntimeWarning: divide by zero encountered in divide
  return 1/np.sqrt(2+3*x-2*x**2, where = x!=2)
